/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class MenuContacto extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuContacto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MenuPri = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        MostrarCon = new javax.swing.JButton();
        RegistrarCon = new javax.swing.JButton();
        ModificarCon = new javax.swing.JButton();
        grafica = new javax.swing.JButton();
        EliminarCon1 = new javax.swing.JButton();
        grafica1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(77, 68, 139));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EP2_i1.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(120, 122, 195));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EP2_i2.png"))); // NOI18N

        MenuPri.setBackground(new java.awt.Color(77, 68, 139));
        MenuPri.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        MenuPri.setForeground(new java.awt.Color(255, 255, 255));
        MenuPri.setText("Menú principal");
        MenuPri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(MenuPri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(MenuPri)
                        .addGap(19, 19, 19))))
        );

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(168, 242, 254));
        jLabel4.setText("Contactos");

        MostrarCon.setBackground(new java.awt.Color(120, 122, 195));
        MostrarCon.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        MostrarCon.setForeground(new java.awt.Color(255, 255, 255));
        MostrarCon.setText("Mostrar contactos");
        MostrarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarConActionPerformed(evt);
            }
        });

        RegistrarCon.setBackground(new java.awt.Color(120, 122, 195));
        RegistrarCon.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        RegistrarCon.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarCon.setText("Registrar un contacto");
        RegistrarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarConActionPerformed(evt);
            }
        });

        ModificarCon.setBackground(new java.awt.Color(120, 122, 195));
        ModificarCon.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        ModificarCon.setForeground(new java.awt.Color(255, 255, 255));
        ModificarCon.setText("Modificar un contacto");
        ModificarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarConActionPerformed(evt);
            }
        });

        grafica.setBackground(new java.awt.Color(120, 122, 195));
        grafica.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        grafica.setForeground(new java.awt.Color(255, 255, 255));
        grafica.setText("Mostrar gráfica");
        grafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficaActionPerformed(evt);
            }
        });

        EliminarCon1.setBackground(new java.awt.Color(120, 122, 195));
        EliminarCon1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        EliminarCon1.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCon1.setText("Eliminar un contacto");
        EliminarCon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCon1ActionPerformed(evt);
            }
        });

        grafica1.setBackground(new java.awt.Color(120, 122, 195));
        grafica1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        grafica1.setForeground(new java.awt.Color(255, 255, 255));
        grafica1.setText("Mostrar gráfica puntos");
        grafica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafica1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RegistrarCon, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModificarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MostrarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EliminarCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(grafica1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegistrarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModificarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grafica1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(MostrarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(EliminarCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPriActionPerformed
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPriActionPerformed

    private void MostrarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarConActionPerformed
        MostrarContactos mc = new MostrarContactos();
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MostrarConActionPerformed

    private void RegistrarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarConActionPerformed
        RegistrarContacto rc = new RegistrarContacto();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistrarConActionPerformed

    private void ModificarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarConActionPerformed
        ModificarContacto mco = new ModificarContacto();
        mco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ModificarConActionPerformed

    private void graficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficaActionPerformed
        GraficaContactoNumeros g = new GraficaContactoNumeros();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_graficaActionPerformed

    private void EliminarCon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCon1ActionPerformed
        EliminarContacto ec = new EliminarContacto();
        ec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarCon1ActionPerformed

    private void grafica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafica1ActionPerformed
        GraficaContactoNumerosP g = new GraficaContactoNumerosP();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_grafica1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarCon1;
    private javax.swing.JButton MenuPri;
    private javax.swing.JButton ModificarCon;
    private javax.swing.JButton MostrarCon;
    private javax.swing.JButton RegistrarCon;
    private javax.swing.JButton grafica;
    private javax.swing.JButton grafica1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
